### ISSUE TITLE
找不到 Exchange.DYDX

### ISSUE THREAD

**Issue by solobat** [vnpy/vnpy_dydx#2]
执行 `python .\script\run.py`  时报以下错误:
```
Traceback (most recent call last):
  File ".\script\run.py", line 5, in <module>
    from vnpy_dydx import DydxGateway
  File "C:\vnstudio\lib\site-packages\vnpy_dydx-2021.8.26s-py3.7.egg\vnpy_dydx\__init__.py", line 1, in <module>
    from .dydx_gateway import DydxGateway
  File "C:\vnstudio\lib\site-packages\vnpy_dydx-2021.8.26s-py3.7.egg\vnpy_dydx\dydx_gateway.py", line 112, in <module>
    class DydxGateway(BaseGateway):
  File "C:\vnstudio\lib\site-packages\vnpy_dydx-2021.8.26s-py3.7.egg\vnpy_dydx\dydx_gateway.py", line 129, in DydxGateway
    exchanges: Exchange = [Exchange.DYDX]
  File "C:\vnstudio\lib\enum.py", line 348, in __getattr__
    raise AttributeError(name) from None
AttributeError: DYDX
```

**Comment by vnpy** [comment]
请在2.6.0版本发布后再使用vnpy_dydx
